name: "Linux Server Power Manager"
version: "1.0.0"
slug: "linux_server_manager"
description: "Manage and safely shut down remote Linux servers using SSH and Smart Plugs."
arch:
  - amd64
  - armv7
  - aarch64
startup: services
boot: auto
ingress: true
ingress_port: 8000
panel_icon: "mdi:server"
panel_title: "Linux Manager"
host_network: true
homeassistant_api: true
options:
  servers: []
schema:
  servers:
    - name: str
      host: str
      user: str
      password: password
      plug_entity: str
